### PR TITLE
Fix various bugs around CR reconcilation, state determination, events and error handling

### LINKED ISSUE #78: Investigate issue where delete CR's (specifically scalingstate) are being logged after they are gone
When a scalingstate is created and then deleted at some later point the operator keeps logging that it can't find it. It's probably from the watcher from the operator SDK.

> 2021-06-04T15:26:28.472+0200	ERROR	controller-runtime.manager.controller.scalingstate	Reconciler error	{"reconciler group": "scaling.prescale.com", "reconciler kind": "ScalingState", "name": "scalingstate-product", "namespace": "default", "error": "ScalingState.scaling.prescale.com \"scalingstate-product\" not found"}
github.com/go-logr/zapr.(*zapLogger).Error
	/home/richter/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/home/richter/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:267
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/home/richter/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:235
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1
	/home/richter/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:198
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1
	/home/richter/go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/util/wait/wait.go:185
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	/home/richter/go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	/home/richter/go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/home/richter/go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext
	/home/richter/go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/util/wait/wait.go:185
k8s.io/apimachinery/pkg/util/wait.UntilWithContext
	/home/richter/go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/util/wait/wait.go:99

### LINKED ISSUE #93: Fix issue where dryrun shows updates from namespaces/deployments that would not be affected
To reproduce:

Create a cluster with multiple namespaces deployment and scalingclasses.
Do a dryrun on one of the scalingclasses.
The dryrun event will show info of non-affected namespaces/deployments

### LINKED ISSUE #97: When a resourcequota is deleted or edited, the operator doesn't reconcile, not solving potential desired states
Right now when someones resolves a RQ violation with removing a RQ or editing it the operator doesn't react and doesn't scale to desired state.

There are two ways to fix this: 

- Add a resourcequota controller that triggers reconcile upon an edit or delete.
- Use the failure mode feature of the operator, put the affected ScalingItems in failure mode and retry every minute to see if the RQ violation has been resolved

### LINKED ISSUE #98: When a resource is step scaling, the interception doesn't work
When a resource is being step scaled and an update would change it's DesiredReplicaCount, the update doesn't translate properly to the step scaler.

### PR DESCRIPTION
**Pull request by PathogenDE**
Bugfix branch that resolves several issues

closes #98 
closes #93
closes #78

For details of the issues resolved see the issues themselves.

In general:
Improved certain events around custom resources that would lead to undesired states.
Improved logging and error handling
Improved Event reporting (only show affected resources)

### CODE REVIEW

File: internal/resources/common.go [hunk 1]
```diff
@@ -157,9 +158,18 @@ func DetermineDesiredReplicas(items []g.ScalingInfo) ([]g.ScalingInfo, error) {
...
 			// TODO here we should do priority filtering, and go down one level of priority to find the lowest set one.
 			// We will ignore any that are not set
-			log.WithValues("set states", stateReplicas).
-				WithValues("state", item.State).
-				Info(fmt.Sprintf("State %s could not be found on scalingItem %s in namespace %s", item.State, item.Name, item.Namespace))
+
+			if item.State == "" {
+				log.WithValues("set states", stateReplicas).
+					WithValues("state", item.State).
+					Info(fmt.Sprintf("No determined state on scalingItem %s in namespace %s! Skipping desiredreplica determination", item.Name, item.Namespace))
```
Comment (chris-cmsoft) [inline internal/resources/common.go:165]: Space between desired & replica

**Review by chris-cmsoft — APPROVED** [review]
LGTM
